version: '2.1'
services:
  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: mion312/demo-config
    restart: always
    ports:
    - 8888:80
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: mion312/demo-registry
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8763:80
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_USERNAME: user
    image: mion312/demo-auth
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: mion312/demo-gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8082:80
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  app-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      APP_SERVICE_PASSWORD: $APP_SERVICE_PASSWORD
    image: mion312/demo-app
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"
