logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/heartbeat
  name: heartbeat
  keepfiles: 7
  permissions: 0644

heartbeat.monitors:
  - type: http
    enable: true
    name: "ElasticSearch"
    schedule: '@every 10s'
    urls:
      - "${ELK_URL}"
    ssl.verification_mode: none
    check.response.status: 200

processors:
  #- add_docker_metadata: ~
  - add_host_metadata: ~

output.elasticsearch:
  enabled: true
  hosts: ["${ELK_HOST}:${ELK_PORT}"]
  loadbalancer: true
  ssl.verification_mode: none

setup.kibana:
  enabled: true
  host: "${KIBANA_HOST}:${KIBANA_PORT}"
  protocol: "https"
  ssl.verification_mode: none