eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:80/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:80/uaa/users/current